### ISSUE TITLE
Welcome screen asks for host name, but cannot connect by host name

### ISSUE THREAD

**Issue by skrupenin** [web-pal/chronos-timetracker#103]
## Expected Behavior
1. Welcome screen asks for host name
2. User enters host name: jira.company.com
3. All goes well

## Actual Behavior
1. Welcome screen asks for host name
2. User enters host name: jira.company.com
3. Login fails
4. User pushes Back
5. User enters http://jira.company.com
6. Now all goes well

## Solution
change title to "Enter JIRA URL"
verify entered value to and URL mask

## Specifications

  - Chronos-timetracker version:
  - OS:

**Comment by Architektor** [comment]
It should work fine, can you please open login debugging tool by pressing 'Can not login' hint under the login form. And post the logs from failing login here?

**Comment by skrupenin** [comment]
Auth debug console 📺
Login request...
host: z.alfakit.ru
protocol: https
port:
path_prefix: /
username: skrupenin
password: ***
{
 "options": {
   "uri": "https://z.alfakit.ru/rest/api/2/myself",
   "method": "GET",
   "json": true,
   "followAllRedirects": true,
   "debug": true,
   "rejectUnauthorized": false,
   "auth": {
     "user": "skrupenin",
     "pass": «-----",
     "password": "***"
   }
 },
 "request": {
   "headers": {
     "host": "z.alfakit.ru",
     "authorization": "***",
     "accept": "application/json"
   }
 },
 "response": {
   "headers": {
     "date": "Tue, 27 Mar 2018 14:16:01 GMT",
     "server": "Apache-Coyote/1.1",
     "x-asen": "SEN-7239305",
     "x-seraph-loginreason": "AUTHENTICATION_DENIED",
     "www-authenticate": "OAuth realm=\"https%3A%2F%2Fsupport.kontur.ru\"",
     "content-type": "text/html;charset=utf-8",
     "content-language": "en",
     "content-length": "1116",
     "connection": "close"
   }
 }
}
Log in to your account
Enter your teamPlease fill in your JIRA host
Can not authenticate user. Please try again
Continue
Enter your credentialsPlease fill in your JIRA accountCan not authenticate user. Please try again
Continue
Back
Can not log in?
Flag notifications

--
С уважением,
Сергей Владимирович Крупенин

**Comment by mahmoudbahaa** [comment]
I think the problem it attempt using https by default so http must be explicitly specified, maybe it should fallback and try http if https login fails instead of just throwing can't login issue

**Comment by VladimirPal** [comment]
@mahmoudbahaa @skrupenin Hi! Could you check 2.8.1, please? All types of authorization should work
