### ISSUE TITLE
Possible to add worklog without worklog comment

### ISSUE THREAD

**Issue by skrupenin** [web-pal/chronos-timetracker#104]
## Expected Behavior
checked on "Forbid sending worklog without comment"
hit Add worklog
enter values, and no worklog comment
hit Log work
Get error message

## Actual Behavior
checked on "Forbid sending worklog without comment"
hit Add worklog
enter values, and no worklog comment
hit Log work
got recorded worklog with no comment https://monosnap.com/file/QiPoHfxdGdAvlZbPhRXqJaOhsi5tIz

## Specifications

  - Chronos-timetracker version:
  - OS:

**Comment by Architektor** [comment]
closed in v2.7.0
