### ISSUE TITLE
Cannot log in- again

### ISSUE THREAD

**Issue by majsternc** [web-pal/chronos-timetracker#107]
## Actual Behavior

Login request...
host: jaga.ncdc
protocol: http
port: 8081
path_prefix: /jira/
username: majster
password: ***
{
  "options": {
    "uri": "http://jaga.ncdc:8081/jira/rest/api/2/myself",
    "method": "GET",
    "json": true,
    "followAllRedirects": true,
    "debug": true,
    "rejectUnauthorized": false,
    "auth": {
      "user": "majster",
      "pass": "dupa",
      "password": "***"
    }
  },
  "request": {
    "headers": {
      "host": "jaga.ncdc:8081",
      "authorization": "***",
      "accept": "application/json"
    }
  },
  "response": {
    "headers": {
      "x-arequestid": "761x1975444x1",
      "x-asen": "SEN-232341",
      "set-cookie": [
        "JSESSIONID=042B5229A5873BA22A9B67C576DF18BE;path=/jira;HttpOnly"
      ],
      "x-seraph-loginreason": "AUTHENTICATION_DENIED",
      "www-authenticate": "OAuth realm=\"https%3A%2F%2Fjira.ncdc.pl%2Fjira\"",
      "x-asessionid": "1u4mt3q",
      "x-content-type-options": "nosniff",
      "x-authentication-denied-reason": "CAPTCHA_CHALLENGE; login-url=https://jira.ncdc.pl/jira/login.jsp",
      "content-type": "text/html;charset=UTF-8",
      "transfer-encoding": "chunked",
      "date": "Mon, 16 Apr 2018 10:41:08 GMT",
      "connection": "close"
    }
  }
}
## Steps to Reproduce the Problem

  1. enter address
  1. enter login
  1. enter password

## Specifications

  - Chronos-timetracker version: 2.7.3
  - OS: Ubuntu gnome newest version

**Comment by VladimirPal** [comment]
@majsternc Hi! Could you check 2.8.1, please? All types of authorization should works now.

**Comment by majsternc** [comment]
Works like a charm. Thank you!
