### ISSUE TITLE
Feature request: Show About (with version) from Help menu

### ISSUE THREAD

**Issue by jhult** [web-pal/chronos-timetracker#111]
## Expected Behavior
I would like to be able to view the current version of the app from the `Help` menu. Perhaps something like what Chrome has under Help -> About:
![screenshot_20180427_102901](https://user-images.githubusercontent.com/9849069/39367890-12e4786a-4a06-11e8-80ed-b356967eb641.png)

## Actual Behavior
`Help` menu does not show the version

## Steps to Reproduce the Problem
View the `Help` menu

## Specifications

  - Chronos-timetracker version: 2.7.3
  - OS: Ubuntu 17.10 x64

**Comment by Architektor** [comment]
You can view Chronos Version by clicking Chronos>About Chronos from the menu
<img width="284" alt="blank_skitch_document" src="https://user-images.githubusercontent.com/4680555/39368091-5ae73716-4a41-11e8-83f9-f2cb2dd28269.png">

**Comment by jhult** [comment]
I don't appear to have that option in my menu...

![screenshot_20180427_104302](https://user-images.githubusercontent.com/9849069/39368559-e3614d6e-4a07-11e8-93d6-6023e078da69.png)

**Comment by jhult** [comment]
It looks like the menu might be different on macOS vs Linux.
