### ISSUE TITLE
New and Edit does not work at all

### ISSUE THREAD

**Issue by btstream** [web-pal/chronos-timetracker#118]
I am using Chronos with jira 7.3.6. When click New and Edit, I get a white screen and waiting and waiting....

Just like the screenshot.
![screenshot_20180629_180248](https://user-images.githubusercontent.com/380671/42086842-ee28c970-7bc6-11e8-9bcd-9c63d888ced7.png)

**Comment by tonylee2016** [comment]
same thing here

**Comment by VladimirPal** [comment]
@btstream @tonylee2016 Hi! Could you check 2.8.1, please?
