### ISSUE TITLE
Cannot login (Can not authenticate user)

### ISSUE THREAD

**Issue by jabulon** [web-pal/chronos-timetracker#119]
## Expected Behavior
Logon succeeds

## Actual Behavior
 Getting the message "Can not authenticate user. Please try again"
I'm logging in correctly to this hostname via Chrome. The username and password are correct - tried inserting manually into the browser after logoff.
The Auth debug console shows:
```
Login request...
host: nndevtools
protocol: http
port: 8080
path_prefix: /
username: my_user_name
password: ***
{
  "options": {
    "auth": {
      "pass": "my_password",
      "password": "***",
      "user": "my_user_name"
    },
    "debug": true,
    "followAllRedirects": true,
    "json": true,
    "method": "GET",
    "rejectUnauthorized": false,
    "uri": "http://nndevtools:8080/rest/api/2/myself"
  },
  "request": {
    "headers": {
      "accept": "application/json",
      "authorization": "***",
      "host": "nndevtools:8080"
    }
  },
  "response": {
    "headers": {
      "connection": "close",
      "content-type": "text/html;charset=UTF-8",
      "date": "Sun, 19 Aug 2018 09:22:08 GMT",
      "server": "Apache-Coyote/1.1",
      "set-cookie": [
        "JSESSIONID=mysession_id_was_here_but_im_paranaoid; Path=/; HttpOnly"
      ],
      "transfer-encoding": "chunked",
      "x-arequestid": "742x129263x1",
      "x-asessionid": "1mjq1z4",
      "x-content-type-options": "nosniff",
      "x-seraph-loginreason": "OK"
    }
  }
}
```

## Steps to Reproduce the Problem

1. Insert the JIRA URL in the welcome screen: http://nndevtools:8080
2. Insert the correct username and password

## Specifications

  - Chronos-timetracker version: 2.7.3
  - OS: Windows 10

**Comment by fboender** [comment]
I experienced the same problem. For me, the cause was that I had two-factor authentication enabled, which Chronos Timetracker doesn't seem to support. Disabling two-factor authentication fixes this problem, but you will need to keep it disabled, or Chronos Timetracker will stop working.

**Comment by VladimirPal** [comment]
@jabulon @fboender Hi! Could you check 2.8.1, please? All types of authorization should work

**Comment by geekonek** [comment]
Hi, i just tried to connect to two factor protected account and could not login using account password or api token. Tried on 2.8.6. Was this issue resolved? 

Also there is not a single line in auth log window.
