### ISSUE TITLE
Feature request: Temporarily stop time tracker / pause

### ISSUE THREAD

**Issue by Dorlosen** [web-pal/chronos-timetracker#123]
A very handy feature that seems to be missing is to temporarily pause the timer. This is possible in the integrated time tracker inside jira and has been quite helpful. Any plans in adding a similar feature in chronos?

**Comment by ooredroxoo** [comment]
I do not know how useful it would be, because if you pause the timer and resume let say after 30min, it should have it start delayed in 30min or be log as done when you hit stop.

I mean it beacuse in this example you would have a 30min gap inside your worklog, that 30min gap can't be placed inside the worklog, it has to be ajusted at it's start or at it's end.

So in this same example stopping and starting a new one after 30 min makes more sense.

**Comment by ksclarke** [comment]
I came here to request this same thing. I think it would be okay to just take the time from the end of the time block. The alternative is getting a bunch of small logs recorded on the ticket. If I work for three hours and every 30 minutes someone is coming in and talking with me and I want to not have that time recorded as active work I get a bunch of broken up worklogs on the ticket.

I've tried some worklog tools that have recorded lots of 5 and 10 minute worklogs. They've worked around this by allowing worklogs to be merged into one big ticket as an after the fact thing. This big ticket though is the time worked, not the exact hours, which is the same thing as if you just took the paused time off the end of the ticket.

I'd also appreciate a pause being implemented in Chronos (which I'm loving so far). I'm okay with the knowledge that the paused time would be taken off the end of the worked period.

**Comment by Dorlosen** [comment]
@ksclarke Nice that someone finds this functionality useful. It is actually default on the integrated time tracker in Jira, so i use that instead of Chronos now. It is useful because my work environment is flexible. I switch between tasks often while working on a main task. I want to pause the main task if my time is interrupted with something else :)

**Comment by ksclarke** [comment]
Hmm, my work's Jira must not have that plugin (or be up to that version yet). I don't see an integrated tracker in Jira, just a way to manually enter a worklog and time period.

**Comment by Dorlosen** [comment]
Not sure if it's integrated or a plugin. But it looks like this:

![image](https://user-images.githubusercontent.com/36210967/62303773-03d96000-b47d-11e9-971a-1c6526625246.png)

![image](https://user-images.githubusercontent.com/36210967/62303701-e4423780-b47c-11e9-80b2-92def609f306.png)
