### ISSUE TITLE
Desktop client cannot be downloaded

### ISSUE THREAD

**Issue by netqsander** [web-pal/chronos-timetracker#125]
## Expected Behavior
The URL at https://chronos-api.web-pal.com/release/exe should return a file to install the Chronos Timetracker app

## Actual Behavior
The URL at https://chronos-api.web-pal.com/release/exe cannot be reached

## Steps to Reproduce the Problem

  1. Navigate to https://chronos-api.web-pal.com/release/exe

## Specifications

  - Chronos-timetracker version: n/a
  - OS: Any

**Comment by VladimirPal** [comment]
Fixed
