### ISSUE TITLE
Hangs forever waiting on login prompt since last update

### ISSUE THREAD

**Issue by silentdis** [web-pal/chronos-timetracker#128]
## Expected Behavior
Presented with credentials request

## Actual Behavior
spinning wait state forever after entering server

## Steps to Reproduce the Problem

  1. Launch AppImage package for Chronos.
  1. Fill in https://confluence.support.com/jira/
  1. Spins forever waiting. -- Was working fine before update today.

## Specifications

  - Chronos-timetracker version: 2.8.0 according to download
  - OS: Kubuntu 18.04

## Troubleshooting Performed

  - Re-downloaded AppImage package, and relaunched, same issue.
  - Cannot find documentation concerning any settings file I can delete. Falling back to web UI for our JIRA instance which works fine.

**Comment by VladimirPal** [comment]
@silentdis Hi! Could you check 2.8.1, please?

**Comment by silentdis** [comment]
Working fine, thank you!
