### ISSUE TITLE
Can't login on new Version 

### ISSUE THREAD

**Issue by mahmoud-elnaggar** [web-pal/chronos-timetracker#132]
## Expected Behavior
Success Login in Hosted Jira version on our Server

## Actual Behavior
Keeps loading after I write Jira URL on Our Server

## Steps to Reproduce the Problem

  1.Open Chronos 
  2.Write down Jira URL
  3.Click Continue 

## Specifications

  - Chronos-timetracker version: Version 2.8.1 
  - OS: Mojave : version 10.14 (18A391)

**Comment by VladimirPal** [comment]
@mahmoud-elnaggar Could you send an url, please?

**Comment by VladimirPal** [comment]
@mahmoud-elnaggar all previous versions can be found here https://github.com/web-pal/chronos-timetracker/releases
I've installed same jira server version as your(v7.5.2) and can't get any issue.
Is it possible to provide us temporary access to your server, could you create test account without access to private data? If it is send it please to mail.vpal@gmail.com

**Comment by emprise1976** [comment]
I have the same Problem.
1- Jira appears in Small window inside Chronos Screen (like built in WebView)
2- If I quit and restart Chronos I have to do the Login process again.

Chronos 2.7.3. works well


Jira ist Version JIRA v7.2.7

**Comment by VladimirPal** [comment]
@emprise1976 
Is it possible to provide us temporary access to your server, could you create test account without access to private data? If it is, send it please to mail.vpal@gmail.com

**Comment by emprise1976** [comment]
@VladimirPal 
Sorry I am not the Administrator of this Jira instance therefore I can't give you Access.

**Comment by VladimirPal** [comment]
@emprise1976 We going to release a new version today, which intends to fix auth issues, stay in touch, please.

**Comment by mahmoud-elnaggar** [comment]
@VladimirPal  
Me too I can't give you access because I don't have these privileges :) 

And thanks for the new version 👍

**Comment by VladimirPal** [comment]
@emprise1976  @mahmoud-elnaggar Check the latest(2.8.3) version, please.

**Comment by kbni** [comment]
@VladimirPal I have just found out about this app and I can confirm that no version will allow me to log into my Jira instance which is hosted at a URL like this one: v7.12.3

If nobody has provided an on-premise Jira with this configuration, I'll set one up that can be accessed. Please let me know.

**Comment by VladimirPal** [comment]
@kbni It will help us a lot. You can send credentials to mail.vpal@gmail.com

**Comment by VladimirPal** [comment]
@kbni  @mahmoud-elnaggar @emprise1976 Check the latest(2.8.4) version, please.
