### ISSUE TITLE
Cannot sign in to Jira

### ISSUE THREAD

**Issue by Treehopper** [web-pal/chronos-timetracker#133]
## Expected Behavior
Clicking the Continue button upon first sign-in, has any effect.

## Actual Behavior
No effect whatsoever. No entry in the Auth debug console

## Steps to Reproduce the Problem

  1. enter jira host
  1. enter user name and password
  1. click Continue

## Specifications

  - Chronos-timetracker version: 2.7.3
  - OS: Win10

**Comment by VladimirPal** [comment]
@Treehopper Could you try the last version - 2.8.1?

**Comment by Treehopper** [comment]
Actually it worked after I restarted the application. When I check the version now it displays 2.8.1. I assume it updated without me noticing.
Sorry, Google gave me a link (I don't remember) that made it seem liked 2.7.3 is the latest version. 
I think this can be closed.

**Comment by VladimirPal** [comment]
@Treehopper Thanks, feel free to create a new issue with a feature request or bug report.
