### ISSUE TITLE
Chronos restarts all the time - macOS V10.14 // Jira v7.12.0

### ISSUE THREAD

**Issue by piapatricktresp** [web-pal/chronos-timetracker#136]
## Expected Behavior

Chronos is firing up and starting with saved credentials or forces to login

## Actual Behavior

Chronos is firing up, loggin in ( i can see the tasks ) and closes. Any restart leads to same behaviour - no work possible 

## Steps to Reproduce the Problem

  1. Install latest chronos version
  2. start chronos
  3. enter credentials

## Specifications

  - Chronos-timetracker version:  (2.8.3)
  - OS: macOS V10.14

**Comment by VladimirPal** [comment]
Check the latest(2.8.4) version, please. if it will not help try to clear cache.
Chronos -> Clear cache

**Comment by piapatricktresp** [comment]
i confirm that the latest version is working for a couple of ppl 👍 
thx
