### ISSUE TITLE
Chronos needs to log in every start

### ISSUE THREAD

**Issue by emprise1976** [web-pal/chronos-timetracker#139]
## Expected Behavior
Chronos should be logged into the jira instance even after quiting the application.

## Actual Behavior
I Need to Login in again every time I start the application after Windows reboots

## Steps to Reproduce the Problem

  1. Start Chronos and Login
  2. Quit Chronos reboot Windows.
  3. Start Chronos again and Login in again

## Specifications

  - Chronos-timetracker version: 2.8.4
  - OS: Windows 10 x64 1803 Build 17134.376
  - Jira: Jira v. 7.2.7

**Comment by emprise1976** [comment]
I also have the Problem that the application suddenly does a Logout during runtime and no entry will be logged in Jira.

**Comment by VladimirPal** [comment]
@emprise1976  Try 2.8.5, please, logout and then login again(it should fix the issue)

**Comment by emprise1976** [comment]
Issue is fixed thx
