### ISSUE TITLE
Feature Request: Save the filter for each PROJECT, BORADS or SPRINT.

### ISSUE THREAD

**Issue by turnerguo** [web-pal/chronos-timetracker#142]
Firstly, this product is really what I want, it really let us focus on jobs.
But if there're more projects or boards to be managed, it will be very hard to manage the filters, because the filter will reset every time I switch the projects list.
![image](https://user-images.githubusercontent.com/633880/48689455-a4486680-ec05-11e8-9f7e-9742ca54750e.png)
I suggest to change the Close button to Save filters button would be better, like this: [Clear filters] [Save filters]! 😋

**Comment by VladimirPal** [comment]
@turnerguo Thank you for the proposition.
We just need to save filters by default(without save button).
We will do it soon.

**Comment by parmira5** [comment]
I'm new to development/contributing to open source. I'd love to take a shot at this if that's okay.

**Comment by VladimirPal** [comment]
@parmira5 Hi! Thank you for your request, but this feature not quite suitable to start contributing.
