### ISSUE TITLE
https system proxy is not used on mojave

### ISSUE THREAD

**Issue by mteske** [web-pal/chronos-timetracker#147]
## Expected Behavior
chronos uses the proxy server configured in system preferences

## Actual Behavior
chronos tries to directly connect to specified jira server
verified with wireshark
## Steps to Reproduce the Problem

  1. Try to login
  1.
  1.

## Specifications

  - Chronos-timetracker version: 2.8.6
  - OS: OSX Mojave

**Comment by VladimirPal** [comment]
@mteske Hi!
Could you try please 3.0.0-beta, it should be fixed

**Comment by mteske** [comment]
yes, thanks, this works fine for me now.
