### ISSUE TITLE
Can't login possibly due to special character in password

### ISSUE THREAD

**Issue by guskuma** [web-pal/chronos-timetracker#149]
## Expected Behavior
Log in with user and password in our jira server

## Actual Behavior
Can't login: "Unknown Error" and no message in Auth debug console

## Steps to Reproduce the Problem

  1. Fill our jira server address
  1. Fill username
  1. Fill password (contains special characters)

## Specifications

  - Chronos-timetracker version: 2.8.6 x86_64
  - OS: Linux Mint 19.1 MATE

**Comment by VladimirPal** [comment]
@guskuma  Hi!
Could you try please 3.0.0-beta, it should be fixed

**Comment by earlgrei** [comment]
Can confirm 3.0.0-beta working with my password.  Has a special char and did not work previously.

**Comment by guskuma** [comment]
@VladimirPal thank you for your efforts. I confirm it's working for me with the very same password I could not log before.
