### ISSUE TITLE
Can't view thumbnails of attachements in description

### ISSUE THREAD

**Issue by ilya-lopukhin** [web-pal/chronos-timetracker#152]
## Expected Behavior
When i click on a thumbnail, i expect to open a corresponding attachment in a new window.
This window should contain a gallery which contains all attachments from the JIRA issue description
If an attachement in a gallery is not an image which could be viewed, i want to see a file placeholder with a file extension which can be donwnloaded

## Actual Behavior
click on thumbnail opens it in a browser

## Steps to Reproduce the Problem

  1. Open issue with thumbnail
  2. Click on it

## Specifications

  - Chronos-timetracker version: latest
  - OS: any

**Comment by VladimirPal** [comment]
Implemented in 3.0.0
