### ISSUE TITLE
Cannot login with Google using SSO 

### ISSUE THREAD

**Issue by mcharris** [web-pal/chronos-timetracker#153]
## Expected Behavior
Login using an google account with external SSO.  

## Actual Behavior
When selecting "Log in with Google" it sits there with just a loading spinner. You can see our branded SSO Login for a split second and then it disappears to the loading spinner until you close the window. 

## Steps to Reproduce the Problem

  1. At the "Log in to your account" page type in (please message me for the hostname)
  1. Click "Continue"
  1. Select "Log in with Google"
  1. Type in (please message me for a sample email)
  1. Click "Continue"

## Specifications

  - Chronos-timetracker version: 2.8.6
  - OS: MacOS

**Comment by VladimirPal** [comment]
@mcharris Hi!
Could you try please 3.0.0-beta, it should be fixed
https://github.com/web-pal/chronos-timetracker/releases/download/v3.0.0-beta/Chronos-3.0.0-beta.dmg

**Comment by VladimirPal** [comment]
@mcharris Could try 3.0.1 please?
