### ISSUE TITLE
Wrong worklog duration is saved if you stop recording from the menubar icon without bringing Chronos to the foreground

### ISSUE THREAD

**Issue by billfeth** [web-pal/chronos-timetracker#154]
## Expected Behavior
The Chronos menubar item always shows the correct duration when recording time while the Chronos app is in the background, and Chronos records the full duration of my time on a task when I stop recording from the menubar with the Chronos app in the background.

## Actual Behavior
The Chronos menubar item seems to "go to sleep" when the Chronos app is in the background. The time reflected in the menubar item stops updating after the app is backgrounded. When I stop recording from the menubar without first bringing the Chronos app to the foreground, Chronos records the wrong duration (too short) shown in the menubar item.

When bringing the Chronos app to the foreground, the app takes several seconds to "catch up" to the current duration of work. (See attached video)

## Steps to Reproduce the Problem

  1. Start timing a task in Chronos
  2. Hide the Chronos app (or put it in the background so its window is completely covered)
  3. Wait several minutes
      Note that the time on the menubar item does not change after you background the app.
  4. Bring the app to the foreground - watch it catch up
-or-
  3. Hide the app again, and wait several minutes
  4. Press stop on the menubar item without bringing the app to the foreground - the app records the inaccurate time reflected in the menubar

## Specifications

  - Chronos-timetracker version: 2.8.6 (2.8.6)
  - OS: macOS High Sierra 10.13.6 (17G5019)

Video 1 ("catch up"): https://youtu.be/qUuMMf2UHH0
Video 2 (menu bar): https://youtu.be/RykxUOl2epI

**Comment by billfeth** [comment]
Thanks for taking a look!

**Comment by VladimirPal** [comment]
@billfeth Hi! Thank you for the detailed issue.
Could you try please 3.0.0-beta, it should be fixed
https://github.com/web-pal/chronos-timetracker/releases/download/v3.0.0-beta/Chronos-3.0.0-beta.dmg
