### ISSUE TITLE
Code does not display nicely

### ISSUE THREAD

**Issue by jhult** [web-pal/chronos-timetracker#159]
## Expected Behavior
Show text in {code} tags nicely formatted.

## Actual Behavior
Text runs off the page. 

## Steps to Reproduce the Problem

  1. Create a Jira issue with {code} tags
  1. View in Jira and then notice the difference in Chronos

## Specifications

  - Chronos-timetracker version: 3.0.0
  - OS: macOS 10.4.3

**Comment by VladimirPal** [comment]
It displays a little bit different, without highlight, but description return from api in html format, so we display what jira returns, if they fix it, it will work,
