### ISSUE TITLE
Can't set worklog comment.

### ISSUE THREAD

**Issue by ooredroxoo** [web-pal/chronos-timetracker#163]
## Expected Behavior
The worklog comment button should display the worklog comment input field when clicked.

## Actual Behavior
The worklog comment button won't display the worklog comment input field when clicked.

## Steps to Reproduce the Problem

  1. Select an issue.
  2. Click on the play button.
  3. Click on the pencil button.

## GIF Capture

![2019-02-25_13-13-31](https://user-images.githubusercontent.com/1323140/53351233-a0606a80-38ff-11e9-9b12-4c91de47459f.gif)

## Specifications

  - Chronos-timetracker version: 3.0.1
  - OS: Windows 10 Pro

## Notes:

- Already try to unninstall and install again.

**Comment by michaelbeauchemin** [comment]
Seeing the same behavior on OSX - 3.0.1 installed this morning.
