### ISSUE TITLE
Issue list do not obey filter ordering.

### ISSUE THREAD

**Issue by ooredroxoo** [web-pal/chronos-timetracker#164]
## Expected Behavior
When listing issues from a filter with a order condition the list should be ordered following the filter order.

## Actual Behavior
Issues are listed by project first.

## Steps to Reproduce the Problem

  1. Create a filter with priority order that fetch issues on multiple projects.
  2. Set this filter as source for the issue list.
  3. See that the ordering isn't obeyed.

## GIF Capture
![2019-02-25_17-24-28](https://user-images.githubusercontent.com/1323140/53366416-4a50ee80-3922-11e9-92c9-2ea0eb0b516d.gif)

## Specifications

  - Chronos-timetracker version: 3.0.1
  - OS: Windows 10 Pro

**Comment by VladimirPal** [comment]
Jira api doesn't respect jql filter order, we display issues in order which they come.
Someday if jira will fix it, it will work properly.
Parse jql and order it manually will not work cause of pagination.
