### ISSUE TITLE
Idle time alert shows up right after 5 min idle time has passed.

### ISSUE THREAD

**Issue by ooredroxoo** [web-pal/chronos-timetracker#166]
## Expected Behavior
Idle timer should be displayed when user resumes it work any time after 5 min of idle time, displaying the total time ammout that he was idle (with the period).

## Actual Behavior
Idle timer alert is displayed right after 5 min of idle time. The periodo is incorrect and it lost it's style.

## Steps to Reproduce the Problem

  1. Start timer on a target computer.
  2. Wait 5 minutes and 10 seconds without doing anything at the target computer.
  3. See the alert.

## Screenshot
![2019-02-28_12-13-19](https://user-images.githubusercontent.com/1323140/53576632-e6613c80-3b52-11e9-8de2-e323803a3767.png)

## Specifications

  - Chronos-timetracker version: 3.0.1
  - OS: Windows 10 Pro

**Comment by deep9** [comment]
I can also confirm it stopped working after the update. I noticed that in master on 09dc84883284f493759a4c9c18a978bcde0408e4 when playing with the source.
