### ISSUE TITLE
editing issue opens previously edited issue

### ISSUE THREAD

**Issue by w0pr** [web-pal/chronos-timetracker#170]
## Expected Behavior

Edit button should open currently selected issue to be edited

## Actual Behavior

Edit button opens previously edited issue

## Steps to Reproduce the Problem

  1. select issue, edit, save
  2. select other issue, edit
 

## Specifications

  - Chronos-timetracker version: v3.0.1
  - OS: Windows 10 Version	10.0.17134 Build 17134

**Comment by VladimirPal** [comment]
Can't reproduce it, checked on windows, works well
