### ISSUE TITLE
Cant see groupping by user

### ISSUE THREAD

**Issue by shorkin** [web-pal/chronos-timetracker#181]
## Expected Behavior
See worklogs grouped by user in Timeline section

## Actual Behavior
No any worklogs shown (in case of Projects of Issues they are shown to the same day) see video https://take.ms/BuDKD

## Steps to Reproduce the Problem

  1. Go to timeline 
  1. Select grouping by users
  1. No any worklogs shown (in case of Projects of Issues they are shown to the same day)
see video https://take.ms/BuDKD

## Specifications

  - Chronos-timetracker version: latest Jira Server Version:0.2
  - OS: Any

**Comment by VladimirPal** [comment]
@shorkin Will be fixed soon.

**Comment by shorkin** [comment]
Thanks

--
С наилучшими пожеланиями,
Алексей Шоркин

Интернет-агентство "Новый Сайт", www.newsite.by
Тел./факс: (+375 17) 290-35-30, 290-35-32
Velcom (029) 331-0119, МТС (029) 778-0119
Адрес: Беларусь, г. Минск, ул. Берестянская 11
Email: a1@newsite.by  | Skype: alexeyshorkin



ср, 19 июн. 2019 г. в 13:46, Vladimir <notifications@github.com>:

**Comment by VladimirPal** [comment]
Fixed
