### ISSUE TITLE
Issue logging on to jira throu Chronos Windows application

### ISSUE THREAD

**Issue by mib-s** [web-pal/chronos-timetracker#182]
Yesterday it work but today one of my co-workers needed to install chronos and he could not connect. My instance was working but i tried to logout and login again and now i have the samme issue.

## Expected Behavior
chronos should login and show issue list

## Actual Behavior
Stays at login animatinon

## Steps to Reproduce the Problem

  1.Open chronos
  2. Input our jira domain (cloud)
  3. Application just stays with login the animation.
  

## Specifications

  - Chronos version: 3.2.4
  - OS: Windows 10

**Comment by AndrewKevin** [comment]
Experiencing this on `OSX 10.14.5` too

**Comment by VladimirPal** [comment]
@mib-s @AndrewKevin Thank you for the bug report folks! 3.2.5 fixed, check it, please.

**Comment by ramses-bemobile** [comment]
@mib-s @AndrewKevin does the new version has fixed the issue for you? I'm still having the problem with the new version. I have deleted the old version and installed the new one 3.2.5. ¿ @VladimirPal Do i have to take any additional steps to make it work?

**Comment by AndrewKevin** [comment]
@ramses-bemobile `3.2.5` is working for me

**Comment by VladimirPal** [comment]
@ramses-bemobile Try 3.2.6 - it will work.
It's a different issue, Atlassian changed auth form markup and broke our window, so only from 3.2.6 you can auth.
