### ISSUE TITLE
Can not log in

### ISSUE THREAD

**Issue by Bokler** [web-pal/chronos-timetracker#183]
## Expected Behavior
After filling in the field (http://prntscr.com/o4ebza) and clicking the "Continue" button should redirect to the authorization form

## Actual Behavior
infinite loader (http://prntscr.com/o4ed7k)

## Steps to Reproduce the Problem

  1. Enter your team
  2. Press the "Continue" button

## Specifications

  - Chronos-timetracker version: 3.2.4, 3.2.5
  - OS: macOS Mojave Version 10.14.5

**Comment by VladimirPal** [comment]
@Bokler Try 3.2.6 - it will work.
