### ISSUE TITLE
Chronos 3.2.6 login issue

### ISSUE THREAD

**Issue by dmkk3r** [web-pal/chronos-timetracker#184]
## Expected Behavior
Chronos should log user in.

## Actual Behavior
Chronos stays at login mask with loader.

## Steps to Reproduce the Problem

  1. Start Chronos.
  2. Input Jira Domain.
  3. Input user cred.

## Specifications

  - Chronos-timetracker version: 3.2.6
  - OS: Windows 10

**Comment by Amr1977** [comment]
Same issue for me.

**Comment by VladimirPal** [comment]
@Amr1977 @dmkk3r Make sure you use the latest 3.2.6 version. Try to install it again https://github.com/web-pal/chronos-timetracker/releases

What type of authentication are you using? Login/Password or google? Cloud or Server jira?

**Comment by dmkk3r** [comment]
Iam on the latest version. Same problem after reinstall. Login via password on local jira server.

**Comment by VladimirPal** [comment]
@dmkk3r What's you jira server version? Can't reproduce it on my local server.
Could you also try old chronos versions for test

**Comment by VladimirPal** [comment]
@Amr1977 What is your OS? Windows 10?

**Comment by Amr1977** [comment]
@VladimirPal MacOS 10.14, I tried older versions 3.2.3/3.2.5 , didn't work

**Comment by dmkk3r** [comment]
OS: Windows 10
Jira server: 7.13.1

**Comment by VladimirPal** [comment]
@Amr1977 Cloud or Server?

**Comment by dmkk3r** [comment]
I have tested versions 3.2.6, 3.2 and 3.1, none of them has logged in. Is there a way to view the error message? Logs or open the Developer Console?

**Comment by ivanyankov** [comment]
Hi team, I have the same issue.

macOS High Sierra - version 10.13.6

I am using the latest version 3.2.6.

**Comment by Amr1977** [comment]
@VladimirPal Turned to be my firewall settings, (everyone also make sure to use correct domain spelling)

**Comment by dmkk3r** [comment]
I have adjusted the firewall settings, but chronos still can not connect.

Could it be that chronos can not cope with the company proxy?

**Comment by Amr1977** [comment]
@dmkk3r Try using VPN, if you could login then you still have to adjust more options in firewall.

**Comment by VladimirPal** [comment]
@dmkk3r @ivanyankov Do you use any system proxy?

**Comment by dmkk3r** [comment]
The problem was that the Jira server was equipped with a self-signed certificate and access was only forwarded via http. I manually referenced the server via http and it worked.
