### ISSUE TITLE
Idle time keeps adding up once user is back from idle

### ISSUE THREAD

**Issue by deep9** [web-pal/chronos-timetracker#187]
## Expected Behavior
Once the activity resumes, the time should be stopped

## Actual Behavior
The timer keeps on adding time

## Steps to Reproduce the Problem

  1. Start the tracker
  1. Wait ~5 minutes (idle)
  1. Idle popup shows up, time keeps adding

## Specifications

  - Chronos-timetracker version: 3.2.6
  - OS: Windows 10

**Comment by VladimirPal** [comment]
@deep9 check the latest version, please
