### ISSUE TITLE
Not compatible with macOS catalina version.

### ISSUE THREAD

**Issue by FurkanSelvi** [web-pal/chronos-timetracker#191]
Not compatible with macOS catalina version.

![Screen Shot 2019-10-14 at 17 09 22](https://user-images.githubusercontent.com/6359484/66757693-5f749080-eea5-11e9-8fc0-38a48679d423.png)

## Specifications

  - Chronos-timetracker version:4.1.0
  - OS: macOS Catalina 10.15

**Comment by VladimirPal** [comment]
@FurkanSelvi  I've just tried, it works. Seems like apple postponed temporarily requirements to notarization applications.

**Comment by jhult** [comment]
The latest release (4.2.0) works for me on Catalina (10.15.1 - 19B88).

**Comment by kwri-avongluck** [comment]
Not working in 10.15.2.

"“Chronos” can’t be opened because Apple cannot check it for malicious software."

**Comment by kwri-avongluck** [comment]
Workaround:
1. Move app to Applications
2. Right Click, Open. Then choose "Open"
