### ISSUE TITLE
Embedded images not displaying

### ISSUE THREAD

**Issue by VladimirPal** [web-pal/chronos-timetracker#21]
On JIRA, if there is only a image (no text) in the description, the embedded image does not display.

![2018-01-02 - cronos screenshot](https://user-images.githubusercontent.com/555405/34728393-7b5ca866-f562-11e7-9f9d-46f41c2cd9ac.png)

**Comment by VladimirPal** [comment]
I have no idea why it happens, but sometimes it works and sometimes it does not.

<img width="600" alt="fullscreen_1_18_18__11_49_am" src="https://user-images.githubusercontent.com/555405/35091681-e277ab6a-fc45-11e7-8501-578cdcc08bab.png">

**Comment by VladimirPal** [comment]
I've figure out why it happens, jira send us html with media links, but this media available only if you have authorized in your browser. But we are not.
Example link: https://web-pal.atlassian.net/secure/thumbnail/13273/DeliverMD.png
If we use OAuth, it will work.
Somehow we need to authdorized electron requests

**Comment by itpimp** [comment]
Works like a dream on 2.4.6. Thanks Vladimir

Richard from PayThem.Net

**Comment by VladimirPal** [comment]
@itpimp It would be great if you type two words on marketplace reviews - https://marketplace.atlassian.com/plugins/com.web-pal.jira.plugins.chronos/cloud/reviews
something like ```good``` or ```bad``` will be enought, also github star :star: will help us too. Thank you. :pray: :metal:
