### ISSUE TITLE
Worklog start time is saved as if it had started when we hit the stop button.

### ISSUE THREAD

**Issue by ooredroxoo** [web-pal/chronos-timetracker#35]
## Expected Behavior
That the worklog was saved with the start time being the time that we hit start and the end time as being the time we pressed the stop button.

## Actual Behavior
Worklog start time is saved as if it had started when we hit the stop button.

## Steps to Reproduce the Problem

  1. Press play at some issue and start work on something.
  2. After while (like a hour) hit the stop button. 
  3. Check jira worklog start date (the date that it says the worklog had started).

## Specifications

  - Chronos-timetracker version: 2.4.1
  - OS: Windows 10 Professional

**Comment by ooredroxoo** [comment]
I believe that the started parameter isn't being set correctly on this file -> https://github.com/web-pal/chronos-timetracker/blob/master/app/sagas/worklogs.js, for the worklog to be properly logged it should have a started parameter configured as stated here -> https://docs.atlassian.com/software/jira/docs/api/REST/7.6.1/?_ga=2.77754577.477393236.1516008065-2038003441.1510715626#api/2/issue-addWorklog

**Comment by VladimirPal** [comment]
@ooredroxoo Fixed, we'll deploy it on 2.4.3

**Comment by VladimirPal** [comment]
@ooredroxoo It would be great if you type two words on marketplace reviews - https://marketplace.atlassian.com/plugins/com.web-pal.jira.plugins.chronos/cloud/reviews
something like ```good``` or ```bad``` will be enought, also github star :star: will help us too. Thank you. :pray: :metal:

**Comment by ooredroxoo** [comment]
Hello @VladimirPal, 
Reviews published.
