### ISSUE TITLE
Statuses Filter Section doesn't list all available statuses.

### ISSUE THREAD

**Issue by ooredroxoo** [web-pal/chronos-timetracker#46]
## Expected Behavior
The status filter session display all statuses.

## Actual Behavior
The status filter session display (at my instance) only 5 statuses.

## Steps to Reproduce the Problem

  1. Click filter icon on the right side from the search input.
  2. View the number of statuses.

## Specifications

  - Chronos-timetracker version: 2.4.3
  - OS: Windows 10 Pro

Chronos Status Filter Section
![image](https://user-images.githubusercontent.com/1323140/35003583-63bf8ac6-fad4-11e7-91f4-91100367b3b9.png)

Jira statuses list (some of them).
![image](https://user-images.githubusercontent.com/1323140/35003652-955ca9a6-fad4-11e7-964e-af2dcd2a5cd5.png)

**Comment by VladimirPal** [comment]
Do you have issues with missed statuses? The app display only statuses that exists in issues.

**Comment by ooredroxoo** [comment]
Yes I have issues using those statuses.

In my case I wanna filter by itens that are awaiting for support ("Esperando por suporte"), From my 589 issues 23 are on this state.

![image](https://user-images.githubusercontent.com/1323140/35004193-4adcad70-fad6-11e7-82da-7bc2271f4077.png)

![image](https://user-images.githubusercontent.com/1323140/35004256-7e032026-fad6-11e7-928d-d5015acf464b.png)

**Comment by ooredroxoo** [comment]
I also noticed that the status filter change from project to project, my other project seems to be fine, but this is displaying this error.

I had to blur the issue title for security reasons.

**Comment by VladimirPal** [comment]
Thank you, we'll try to figure out and fix

**Comment by VladimirPal** [comment]
It was fixed(development branch).
