### ISSUE TITLE
Ticket search for all projects

### ISSUE THREAD

**Issue by JimTim** [web-pal/chronos-timetracker#48]
## Expected Behavior
If I am searching for a ticket in all projects, I should see a corresponding list. Since this search takes longer, I should get some information about it. It should also be possible to deactivate certain projects for the search.

## Actual Behavior
The search only works per project.

## Steps to Reproduce the Problem
- 

## Specifications

  - Chronos-timetracker version: 2.4.6
  - OS: MacOS

**Comment by feldifux** [comment]
+1 for this issue

**Comment by feldifux** [comment]
as a first step, what would already help is to have a list of all tasks of all projects and make this searchable.
another useful item would be to have a list of recent worklogs across projects.

**Comment by feldifux** [comment]
This would be most flexible, if we could just choose a filter to show the issues, in addition to the current options Projects & Boards. A user can then customize the filter to his liking (e.g. include the unresolved tasks across all projects)

**Comment by feldifux** [comment]
I'd like to +10 for this (one for each team member who is using Chronos here ;)

adding support for filters would also solve https://github.com/web-pal/chronos-timetracker/issues/86

**Comment by Architektor** [comment]
@feldifux @JimTim now the 2.7.0 is out! Please make any favorite filter inside JIRA, and you will be able to use it, edit it and create new JQL filters in Chronos! Works project-wide.

**Comment by Architektor** [comment]
@feldifux @JimTim now the 2.7.0 is out! Please make any favorite filter inside JIRA, and you will be able to use it, edit it and create new JQL filters in Chronos! Works project-wide.
