### ISSUE TITLE
Create jira tickets via Chronos

### ISSUE THREAD

**Issue by JimTim** [web-pal/chronos-timetracker#49]
## Expected Behavior
As a user of Chronos, I want to be able to create tickets for projects via the interface.

## Actual Behavior
I cannot create tickets

## Steps to Reproduce the Problem
-
## Specifications

  - Chronos-timetracker version: 2.4.6
  - OS:

**Comment by VladimirPal** [comment]
Done(develop branch). Will be in the next release.

**Comment by VladimirPal** [comment]
@JimTim We released pre-release version with this functionality you can check it.

**Comment by JimTim** [comment]
Looks very good. Thx

**Comment by VladimirPal** [comment]
@JimTim It would be great if you type two words on marketplace reviews - https://marketplace.atlassian.com/plugins/com.web-pal.jira.plugins.chronos/cloud/reviews
something like ```good``` or ```bad``` will be enought. Thank you. :pray: :metal:
