### ISSUE TITLE
Comment after times were tracked

### ISSUE THREAD

**Issue by JimTim** [web-pal/chronos-timetracker#50]
## Expected Behavior
When I finish tracking on a ticket, I want to see a dialog where I am asked for a comment. This should be optional and can be deactivated by a setting.

## Actual Behavior
Currently, the worklog is saved without comment after the end of the tracking. I have to edit this worklog afterwards.

## Steps to Reproduce the Problem
-
## Specifications

  - Chronos-timetracker version: 2.4.6
  - OS:

**Comment by Architektor** [comment]
@JimTim you can actually set comment if you click pencil icon in tracking bar (see screenshot)
<img width="913" alt="chronos" src="https://user-images.githubusercontent.com/4680555/35387696-73a17740-01d9-11e8-9e8f-8953b497ca0b.png">
