### ISSUE TITLE
If I have a long list of worklogs, I sometimes see the wrong entry

### ISSUE THREAD

**Issue by JimTim** [web-pal/chronos-timetracker#51]
## Expected Behavior
I should always see the correct list of worklogs. The list should also be pageed. This may reduce the number of requests to the Jira server.

## Actual Behavior
Currently you get all worklogs as a long list. Sometimes this list is not correct and shows worklogs twice. Or a worklog content is in the wrong place to the wrong timestamp.

## Steps to Reproduce the Problem

  1. Long list of worklogs (about 50 or more worklogs)
  1. Scrolling in the worklog list
  1. Content is sometimes displayed incorrectly

## Specifications

  - Chronos-timetracker version: 2.4.6
  - OS: MacOS

**Comment by JimTim** [comment]
I can send you a non-public gif. To which address should I send the gif?

**Comment by Architektor** [comment]
@JimTim feel free to send it to vlad@web-pal.com

**Comment by JimTim** [comment]
Your message wasn't delivered to vlad@web-pal.com because the address couldn't be found, or is unable to receive mail. 4.2 MB Gif

**Comment by VladimirPal** [comment]
@JimTim Wrong email, sorry.
Try mail.vpal@gmail.com

**Comment by VladimirPal** [comment]
Fixed(develop branch). Will be in the next release.

**Comment by JimTim** [comment]
Fixed, nice, THX!
