### ISSUE TITLE
Worklog comment will not be reset in case of a new tracker

### ISSUE THREAD

**Issue by JimTim** [web-pal/chronos-timetracker#56]
## Expected Behavior
When I start a new tracker, the comment of the old trackers should no longer be included. Otherwise, an incorrect worklog can occur.

## Actual Behavior
When I start a new tracker, the comment of the old one is included.

## Steps to Reproduce the Problem

  1. Start the tracker and adjust the comment with the Edit button. 
  1. Stop and save the tracker. 
  1. Now start a tracker again with another ticket.
  1. Comment still exists and when you exit the Tracker this comment will be **set.**

## Specifications

  - Chronos-timetracker version: 2.4.6
  - OS: MacOS

**Comment by VladimirPal** [comment]
Done(develop branch). Check next release

**Comment by JimTim** [comment]
working, THX
