### ISSUE TITLE
As a User I would like to search issues using JQL

### ISSUE THREAD

**Issue by ooredroxoo** [web-pal/chronos-timetracker#57]
## Expected Behavior
That we could use the search bar to input JQL and then do a more fine grained search.

## Actual Behavior
Search only works with Issues Keys and Summaries

## Specifications

  - Chronos-timetracker version: 2.4.7
  - OS: Windows 10 Pro

**Comment by Architektor** [comment]
@ooredroxoo now the 2.7.0 is out! Please make any favorite filter inside JIRA, and you will be able to use it, edit it and create new JQL filters in Chronos! Works project-wide.

**Comment by garyttierney** [comment]
~Is this still a supported feature? I haven't been able to find where I can select my JIRA filters.~

Nevermind, I see they appear once you start typing into the project/boards search.
