### ISSUE TITLE
When the project is changed, the search should be reset.

### ISSUE THREAD

**Issue by JimTim** [web-pal/chronos-timetracker#62]
## Expected Behavior
When the project is changed, the search should be reset.

## Actual Behavior
All settings remain in place until they are changed manually.

## Steps to Reproduce the Problem

  1. Go into a project and update the search
  1. change project
  1. Search remains and the first search, after a project change, is also executed with it

## Specifications

  - Chronos-timetracker version: 2.5.0
  - OS: MacOS

**Comment by VladimirPal** [comment]
Done
