### ISSUE TITLE
Replacing clear plugin with reset plugin 

### ISSUE THREAD

**Issue by jamesplease** [web-pal/chronos-timetracker#65]
A quick glance suggests that the [“clear” plugins you have defined](https://redux-resource.js.org/docs/extras/reset-plugin.html) could possibly be replaced with the [reset plugin.](https://redux-resource.js.org/docs/extras/reset-plugin.html)

If you tried that out, and some feature was missing, then perhaps that missing feature could be backported into the core lib to reduce the amount of app code you need to write 🙂 

Also, in the next release (2.5), you will be able to set the resource meta using built-in tools, so the meta plugin that you have can also be removed from the app :v:

Thanks for reading!

**Comment by VladimirPal** [comment]
@jmeas Thanks, i'll try to use reset plugin, also will check new release.

**Comment by VladimirPal** [comment]
Unfortunately we can't use this plugins, because we have indexedList plugin, since we need indexed list for react-virtualized.
