### ISSUE TITLE
The project search should also work with the project key

### ISSUE THREAD

**Issue by JimTim** [web-pal/chronos-timetracker#67]
## Expected Behavior
The project search should also work with the project key.

## Actual Behavior
Currently you can only search for the project name

## Steps to Reproduce the Problem

  1. Search for project names, e. g. Customer Success Management
  1. Ticket then has the project id as ticket id, for example CSM-1
  1. Project search for "CSM" brings but no result

## Specifications

  - Chronos-timetracker version: 2.5.1
  - OS: MAC

**Comment by VladimirPal** [comment]
@JimTim We use jira api for search functionality, and jira do not allow to make search using only project key, i think we can't handle this issue

**Comment by JimTim** [comment]
Where are the projects list fetched in this source code?

https://docs.atlassian.com/DAC/rest/jira/6.1.html#d2e3008
At least the Projectkey / ProjectId is mentioned here.

**Comment by VladimirPal** [comment]
JQL query creating here https://github.com/web-pal/chronos-timetracker/blob/develop/app/sagas/issues.js#L147
Request here https://github.com/web-pal/chronos-timetracker/blob/develop/app/utils/api/issues.js#L44

**Comment by JimTim** [comment]
Ah I see. But I mean the project search / project combo select box on the
top left. I doesn't mean the issue search. Thx

Vladimir <notifications@github.com> schrieb am Mi., 7. Feb. 2018, 17:51:

**Comment by VladimirPal** [comment]
@JimTim I got it now, we'll fix it

**Comment by JimTim** [comment]
Perfect, thank you very much

Vladimir <notifications@github.com> schrieb am Mi., 7. Feb. 2018, 19:14:

**Comment by VladimirPal** [comment]
2.5.4
@JimTim Confirm please if it works

**Comment by JimTim** [comment]
Works
