### ISSUE TITLE
Sprint filter feature is not working for JIRA Server

### ISSUE THREAD

**Issue by addmitriev** [web-pal/chronos-timetracker#68]
Hi team, 

App crashes if I choose sprint in project selector. After reopening app it's still not loading any data and showing blank screen.

My team is using JIRA Server 7.3.1. 
The reason for that unexpected behaviour is that in JIRA Server Rest response there is no field "location" in [getBoard]( https://docs.atlassian.com/jira-software/REST/7.3.1/#agile/1.0/board-getBoard)  method. The "location" field is used by [this file](https://github.com/web-pal/chronos-timetracker/blob/master/app/selectors/projects.js#L50) at least. 

The solution is use [additional endpoint](https://docs.atlassian.com/jira-software/REST/7.3.1/#agile/1.0/board/{boardId}/project) to retrieve projects for board 
## Expected Behaviour
Sprint can be chose as an issue filter.

## Actual Behaviour
App crashes, even after reopen.

## Steps to Reproduce the Problem

  1. Connect to JIRA Server edition v.7.3.1. 
  1. Select board
  1. Select sprint

## Specifications

  - Chronos-timetracker version: 2.5.3 
  - OS: Windows
  - JIRA: Server edition v.7.3.1.

**Comment by VladimirPal** [comment]
Thank you for the detailed issues. We'll fix it soon.

**Comment by VladimirPal** [comment]
2.5.4
@JimTim Confirm please if it works

**Comment by addmitriev** [comment]
👍 Works great! Thank you!

**Comment by VladimirPal** [comment]
@addmitriev It would be great if you type two words on marketplace reviews - https://marketplace.atlassian.com/plugins/com.web-pal.jira.plugins.chronos/cloud/reviews
something like ```good``` or ```bad``` will be enought, also github star :star: will help us too. Thank you. :pray: :metal:
