### ISSUE TITLE
Completely white page after a project has been selected.

### ISSUE THREAD

**Issue by JimTim** [web-pal/chronos-timetracker#69]
## Expected Behavior
After choosing a project, the tickets and everything else should be displayed.

## Actual Behavior
After I have selected a certain project, the complete page will be white.

## Steps to Reproduce the Problem

  1. Select a project 
  1. now everything else will be "white"
  1.

## Specifications

  - Chronos-timetracker version: 2.5.4
  - OS: MacOS

**Comment by JimTim** [comment]
In 2.4.7 the problem does not exist, i. e. it is caused by anything between 2.5. x and 2.5.4. I can also have a look at the error logs later on, about 6 pm German time.

**Comment by VladimirPal** [comment]
@JimTim Thank you for the issue, we'll try figure out the reason.

**Comment by JimTim** [comment]
@VladimirPal Perfect, thank you. Let me know if there's anything I can look up in the console log. It's not really a special project.

**Comment by VladimirPal** [comment]
@JimTim We collect all errors automatically, apiomat.com - it's you?

**Comment by JimTim** [comment]
@VladimirPal In 2.4.7 everything is still working. 2.5.1 shows the white page

**Comment by JimTim** [comment]
Yeah it's me :-) or all of us: -)

**Comment by VladimirPal** [comment]
@JimTim 
Every user is experiencing the issue?
Try to remove storage and launch app again:
```
rm -rf ~/Library/Application\ Support/Chronos/storage
```

**Comment by JimTim** [comment]
Yes, everybody has problems with this project and after that he tries to load the last project, so there is always a white page. I will try to remove the folder now.

**Comment by VladimirPal** [comment]
@JimTim So it happens only with one project?

**Comment by JimTim** [comment]
Yes, maybe because the project key is the same name as the board?
For Example:
Project name: example name
Projectkey: exp
Project Kanban board name: exp

**Comment by JimTim** [comment]
@VladimirPal Is it possible to insert a menu item above to delete the storage? Because it's still working, and the update report is still coming.

**Comment by VladimirPal** [comment]
@JimTim I'm not sure what you mean, after clearing storage everything works?
I have doubt about it.
Could you install 2.5.5 pre-release, it will not fix the issue but give us additional information, so we can fix it.
https://github.com/web-pal/chronos-timetracker/releases/tag/v2.5.5

**Comment by VladimirPal** [comment]
@JimTim Let me know please when you check this project on 2.5.5

**Comment by JimTim** [comment]
Ok, first thanky you ... and I will try it now

**Comment by VladimirPal** [comment]
@JimTim And still white page?

**Comment by JimTim** [comment]
Yes, still white page

**Comment by JimTim** [comment]
action ui/SET_UI_STATE @ 13:44:34.660
redux-logger.js:1  action ui/SET_UI_STATE @ 13:44:34.666
redux-logger.js:1  action ui/SET_UI_STATE @ 13:44:34.675
redux-logger.js:1  action ui/SET_UI_STATE @ 13:44:34.683
redux-logger.js:1  action ui/SET_UI_STATE @ 13:44:34.691
redux-logger.js:1  action ui/SET_UI_STATE @ 13:44:34.698
redux-logger.js:1  action ui/SET_UI_STATE @ 13:44:34.706
redux-logger.js:1  action resources/CLEAR_LIST @ 13:44:34.711
redux-logger.js:1  action issues/REFETCH_REQUEST @ 13:44:34.717
redux-logger.js:1  action resources/CLEAR_LIST @ 13:44:34.722
redux-logger.js:1  action resources/SET_META @ 13:44:34.726
redux-logger.js:1  action resources/SET_META @ 13:44:34.733
redux-logger.js:1  action resources/SET_META @ 13:44:34.758
redux-logger.js:1  action issues/FETCH_REQUEST @ 13:44:34.807
redux-logger.js:1  action READ_RESOURCES_PENDING @ 13:44:34.811
redux-logger.js:1  action resources/SET_META @ 13:44:34.999
redux-logger.js:1  action issues/FETCH_REQUEST @ 13:44:35.071
createClassProxy.js:95 Uncaught TypeError: Function.prototype.bind.apply(...) is not a constructor
    at createClassProxy.js:95
    at instantiate (createClassProxy.js:103)
    at IssueItem (eval at proxyClass (createClassProxy.js:110), <anonymous>:4:17)
    at mountIndeterminateComponent (react-dom.development.js:8032)
    at beginWork (react-dom.development.js:8221)
    at performUnitOfWork (react-dom.development.js:10224)
    at workLoop (react-dom.development.js:10288)
    at HTMLUnknownElement.callCallback (react-dom.development.js:542)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:581)
    at invokeGuardedCallback (react-dom.development.js:438)
(anonymous) @ createClassProxy.js:95
instantiate @ createClassProxy.js:103
IssueItem @ VM1513:4
mountIndeterminateComponent @ react-dom.development.js:8032
beginWork @ react-dom.development.js:8221
performUnitOfWork @ react-dom.development.js:10224
workLoop @ react-dom.development.js:10288
callCallback @ react-dom.development.js:542
invokeGuardedCallbackDev @ react-dom.development.js:581
invokeGuardedCallback @ react-dom.development.js:438
renderRoot @ react-dom.development.js:10366
performWorkOnRoot @ react-dom.development.js:11014
performWork @ react-dom.development.js:10967
requestWork @ react-dom.development.js:10878
scheduleWorkImpl @ react-dom.development.js:10732
scheduleWork @ react-dom.development.js:10689
enqueueSetState @ react-dom.development.js:6212
Component.setState @ react.development.js:237
onStateChange @ connectAdvanced.js:215
onStateChange @ createPrototypeProxy.js:44
notify @ Subscription.js:28
notifyNestedSubs @ Subscription.js:67
onStateChange @ connectAdvanced.js:212
onStateChange @ createPrototypeProxy.js:44
notify @ Subscription.js:28
notifyNestedSubs @ Subscription.js:67
onStateChange @ connectAdvanced.js:212
onStateChange @ createPrototypeProxy.js:44
dispatch @ createStore.js:178
dispatch @ VM97:2
(anonymous) @ redux-logger.js:1
(anonymous) @ middleware.js:71
dispatch @ applyMiddleware.js:38
(anonymous) @ utils.js:283
(anonymous) @ proc.js:499
exec @ scheduler.js:23
flush @ scheduler.js:64
asap @ scheduler.js:37
runPutEffect @ proc.js:496
runEffect @ proc.js:445
next @ proc.js:325
currCb @ proc.js:398
end @ proc.js:366
task.cont @ proc.js:109
next @ proc.js:331
proc @ proc.js:280
resolveIterator @ proc.js:466
runCallEffect @ proc.js:527
runEffect @ proc.js:445
next @ proc.js:325
currCb @ proc.js:398
end @ proc.js:366
task.cont @ proc.js:109
next @ proc.js:331
proc @ proc.js:280
resolveIterator @ proc.js:466
runCallEffect @ proc.js:527
runEffect @ proc.js:445
next @ proc.js:325
currCb @ proc.js:398
_tickCallback @ internal/process/next_tick.js:109
react-dom.development.js:9747 The above error occurred in the <IssueItem> component:
    in IssueItem
    in div
    in div (created by Grid)
    in div (created by Grid)
    in Grid (created by List)
    in List (created by AutoSizer)
    in div (created by AutoSizer)
    in AutoSizer (created by InfiniteLoader)
    in InfiniteLoader (created by SidebarAllItems)
    in div (created by styled.div)
    in styled.div (created by SidebarAllItems)
    in SidebarAllItems (created by lifecycle(SidebarAllItems))
    in lifecycle(SidebarAllItems) (created by withHandlers(lifecycle(SidebarAllItems)))
    in withHandlers(lifecycle(SidebarAllItems)) (created by Connect(withHandlers(lifecycle(SidebarAllItems))))
    in Connect(withHandlers(lifecycle(SidebarAllItems))) (created by Sidebar)
    in div (created by styled.div)
    in styled.div (created by Sidebar)
    in div (created by styled.div)
    in styled.div (created by Sidebar)
    in Sidebar (created by Connect(Sidebar))
    in Connect(Sidebar) (created by Main)
    in div (created by styled.div)
    in styled.div (created by Styled(styled.div))
    in Styled(styled.div) (created by Main)
    in div (created by styled.div)
    in styled.div (created by Styled(styled.div))
    in Styled(styled.div) (created by Main)
    in t (created by Main)
    in Main (created by App)
    in div (created by styled.div)
    in styled.div (created by App)
    in div (created by styled.div)
    in styled.div (created by App)
    in App (created by Connect(App))
    in Connect(App)
    in Provider
    in AppContainer

React will try to recreate this component tree from scratch using the error boundary you provided, AppContainer.
logCapturedError @ react-dom.development.js:9747
captureError @ react-dom.development.js:10540
renderRoot @ react-dom.development.js:10391
performWorkOnRoot @ react-dom.development.js:11014
performWork @ react-dom.development.js:10967
requestWork @ react-dom.development.js:10878
scheduleWorkImpl @ react-dom.development.js:10732
scheduleWork @ react-dom.development.js:10689
enqueueSetState @ react-dom.development.js:6212
Component.setState @ react.development.js:237
onStateChange @ connectAdvanced.js:215
onStateChange @ createPrototypeProxy.js:44
notify @ Subscription.js:28
notifyNestedSubs @ Subscription.js:67
onStateChange @ connectAdvanced.js:212
onStateChange @ createPrototypeProxy.js:44
notify @ Subscription.js:28
notifyNestedSubs @ Subscription.js:67
onStateChange @ connectAdvanced.js:212
onStateChange @ createPrototypeProxy.js:44
dispatch @ createStore.js:178
dispatch @ VM97:2
(anonymous) @ redux-logger.js:1
(anonymous) @ middleware.js:71
dispatch @ applyMiddleware.js:38
(anonymous) @ utils.js:283
(anonymous) @ proc.js:499
exec @ scheduler.js:23
flush @ scheduler.js:64
asap @ scheduler.js:37
runPutEffect @ proc.js:496
runEffect @ proc.js:445
next @ proc.js:325
currCb @ proc.js:398
end @ proc.js:366
task.cont @ proc.js:109
next @ proc.js:331
proc @ proc.js:280
resolveIterator @ proc.js:466
runCallEffect @ proc.js:527
runEffect @ proc.js:445
next @ proc.js:325
currCb @ proc.js:398
end @ proc.js:366
task.cont @ proc.js:109
next @ proc.js:331
proc @ proc.js:280
resolveIterator @ proc.js:466
runCallEffect @ proc.js:527
runEffect @ proc.js:445
next @ proc.js:325
currCb @ proc.js:398
_tickCallback @ internal/process/next_tick.js:109
AppContainer.dev.js:95 TypeError: Function.prototype.bind.apply(...) is not a constructor
    at createClassProxy.js:95
    at instantiate (createClassProxy.js:103)
    at IssueItem (eval at proxyClass (createClassProxy.js:110), <anonymous>:4:17)
    at mountIndeterminateComponent (react-dom.development.js:8032)
    at beginWork (react-dom.development.js:8221)
    at performUnitOfWork (react-dom.development.js:10224)
    at workLoop (react-dom.development.js:10288)
    at HTMLUnknownElement.callCallback (react-dom.development.js:542)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:581)
    at invokeGuardedCallback (react-dom.development.js:438)
render @ AppContainer.dev.js:95
finishClassComponent @ react-dom.development.js:7873
updateClassComponent @ react-dom.development.js:7850
beginWork @ react-dom.development.js:8225
performUnitOfWork @ react-dom.development.js:10224
slowWorkLoopThatChecksForFailedWork @ react-dom.development.js:10310
workLoop @ react-dom.development.js:10278
callCallback @ react-dom.development.js:542
invokeGuardedCallbackDev @ react-dom.development.js:581
invokeGuardedCallback @ react-dom.development.js:438
renderRoot @ react-dom.development.js:10366
performWorkOnRoot @ react-dom.development.js:11014
performWork @ react-dom.development.js:10967
requestWork @ react-dom.development.js:10878
scheduleWorkImpl @ react-dom.development.js:10732
scheduleWork @ react-dom.development.js:10689
enqueueSetState @ react-dom.development.js:6212
Component.setState @ react.development.js:237
onStateChange @ connectAdvanced.js:215
onStateChange @ createPrototypeProxy.js:44
notify @ Subscription.js:28
notifyNestedSubs @ Subscription.js:67
onStateChange @ connectAdvanced.js:212
onStateChange @ createPrototypeProxy.js:44
notify @ Subscription.js:28
notifyNestedSubs @ Subscription.js:67
onStateChange @ connectAdvanced.js:212
onStateChange @ createPrototypeProxy.js:44
dispatch @ createStore.js:178
dispatch @ VM97:2
(anonymous) @ redux-logger.js:1
(anonymous) @ middleware.js:71
dispatch @ applyMiddleware.js:38
(anonymous) @ utils.js:283
(anonymous) @ proc.js:499
exec @ scheduler.js:23
flush @ scheduler.js:64
asap @ scheduler.js:37
runPutEffect @ proc.js:496
runEffect @ proc.js:445
next @ proc.js:325
currCb @ proc.js:398
end @ proc.js:366
task.cont @ proc.js:109
next @ proc.js:331
proc @ proc.js:280
resolveIterator @ proc.js:466
runCallEffect @ proc.js:527
runEffect @ proc.js:445
next @ proc.js:325
currCb @ proc.js:398
end @ proc.js:366
task.cont @ proc.js:109
next @ proc.js:331
proc @ proc.js:280
resolveIterator @ proc.js:466
runCallEffect @ proc.js:527
runEffect @ proc.js:445
next @ proc.js:325
currCb @ proc.js:398
_tickCallback @ internal/process/next_tick.js:109
createClassProxy.js:95 Uncaught TypeError: Function.prototype.bind.apply(...) is not a constructor
    at createClassProxy.js:95
    at instantiate (createClassProxy.js:103)
    at IssueItem (eval at proxyClass (createClassProxy.js:110), <anonymous>:4:17)
    at mountIndeterminateComponent (react-dom.development.js:8032)
    at beginWork (react-dom.development.js:8221)
    at performUnitOfWork (react-dom.development.js:10224)
    at slowWorkLoopThatChecksForFailedWork (react-dom.development.js:10310)
    at workLoop (react-dom.development.js:10278)
    at HTMLUnknownElement.callCallback (react-dom.development.js:542)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:581)
(anonymous) @ createClassProxy.js:95
instantiate @ createClassProxy.js:103
IssueItem @ VM1513:4
mountIndeterminateComponent @ react-dom.development.js:8032
beginWork @ react-dom.development.js:8221
performUnitOfWork @ react-dom.development.js:10224
slowWorkLoopThatChecksForFailedWork @ react-dom.development.js:10310
workLoop @ react-dom.development.js:10278
callCallback @ react-dom.development.js:542
invokeGuardedCallbackDev @ react-dom.development.js:581
invokeGuardedCallback @ react-dom.development.js:438
renderRoot @ react-dom.development.js:10366
performWorkOnRoot @ react-dom.development.js:11014
performWork @ react-dom.development.js:10967
requestWork @ react-dom.development.js:10878
scheduleWorkImpl @ react-dom.development.js:10732
scheduleWork @ react-dom.development.js:10689
enqueueSetState @ react-dom.development.js:6212
Component.setState @ react.development.js:237
onStateChange @ connectAdvanced.js:215
onStateChange @ createPrototypeProxy.js:44
notify @ Subscription.js:28
notifyNestedSubs @ Subscription.js:67
onStateChange @ connectAdvanced.js:212
onStateChange @ createPrototypeProxy.js:44
notify @ Subscription.js:28
notifyNestedSubs @ Subscription.js:67
onStateChange @ connectAdvanced.js:212
onStateChange @ createPrototypeProxy.js:44
dispatch @ createStore.js:178
dispatch @ VM97:2
(anonymous) @ redux-logger.js:1
(anonymous) @ middleware.js:71
dispatch @ applyMiddleware.js:38
(anonymous) @ utils.js:283
(anonymous) @ proc.js:499
exec @ scheduler.js:23
flush @ scheduler.js:64
asap @ scheduler.js:37
runPutEffect @ proc.js:496
runEffect @ proc.js:445
next @ proc.js:325
currCb @ proc.js:398
end @ proc.js:366
task.cont @ proc.js:109
next @ proc.js:331
proc @ proc.js:280
resolveIterator @ proc.js:466
runCallEffect @ proc.js:527
runEffect @ proc.js:445
next @ proc.js:325
currCb @ proc.js:398
end @ proc.js:366
task.cont @ proc.js:109
next @ proc.js:331
proc @ proc.js:280
resolveIterator @ proc.js:466
runCallEffect @ proc.js:527
runEffect @ proc.js:445
next @ proc.js:325
currCb @ proc.js:398
_tickCallback @ internal/process/next_tick.js:109
react-dom.development.js:9747 The above error occurred in the <IssueItem> component:
    in IssueItem
    in div
    in div (created by Grid)
    in div (created by Grid)
    in Grid (created by List)
    in List (created by AutoSizer)
    in div (created by AutoSizer)
    in AutoSizer (created by InfiniteLoader)
    in InfiniteLoader (created by SidebarAllItems)
    in div (created by styled.div)
    in styled.div (created by SidebarAllItems)
    in SidebarAllItems (created by lifecycle(SidebarAllItems))
    in lifecycle(SidebarAllItems) (created by withHandlers(lifecycle(SidebarAllItems)))
    in withHandlers(lifecycle(SidebarAllItems)) (created by Connect(withHandlers(lifecycle(SidebarAllItems))))
    in Connect(withHandlers(lifecycle(SidebarAllItems))) (created by Sidebar)
    in div (created by styled.div)
    in styled.div (created by Sidebar)
    in div (created by styled.div)
    in styled.div (created by Sidebar)
    in Sidebar (created by Connect(Sidebar))
    in Connect(Sidebar) (created by Main)
    in div (created by styled.div)
    in styled.div (created by Styled(styled.div))
    in Styled(styled.div) (created by Main)
    in div (created by styled.div)
    in styled.div (created by Styled(styled.div))
    in Styled(styled.div) (created by Main)
    in t (created by Main)
    in Main (created by App)
    in div (created by styled.div)
    in styled.div (created by App)
    in div (created by styled.div)
    in styled.div (created by App)
    in App (created by Connect(App))
    in Connect(App)
    in Provider
    in AppContainer

This error was initially handled by the error boundary AppContainer.
Recreating the tree from scratch failed so React will unmount the tree.
logCapturedError @ react-dom.development.js:9747
captureError @ react-dom.development.js:10540
renderRoot @ react-dom.development.js:10391
performWorkOnRoot @ react-dom.development.js:11014
performWork @ react-dom.development.js:10967
requestWork @ react-dom.development.js:10878
scheduleWorkImpl @ react-dom.development.js:10732
scheduleWork @ react-dom.development.js:10689
enqueueSetState @ react-dom.development.js:6212
Component.setState @ react.development.js:237
onStateChange @ connectAdvanced.js:215
onStateChange @ createPrototypeProxy.js:44
notify @ Subscription.js:28
notifyNestedSubs @ Subscription.js:67
onStateChange @ connectAdvanced.js:212
onStateChange @ createPrototypeProxy.js:44
notify @ Subscription.js:28
notifyNestedSubs @ Subscription.js:67
onStateChange @ connectAdvanced.js:212
onStateChange @ createPrototypeProxy.js:44
dispatch @ createStore.js:178
dispatch @ VM97:2
(anonymous) @ redux-logger.js:1
(anonymous) @ middleware.js:71
dispatch @ applyMiddleware.js:38
(anonymous) @ utils.js:283
(anonymous) @ proc.js:499
exec @ scheduler.js:23
flush @ scheduler.js:64
asap @ scheduler.js:37
runPutEffect @ proc.js:496
runEffect @ proc.js:445
next @ proc.js:325
currCb @ proc.js:398
end @ proc.js:366
task.cont @ proc.js:109
next @ proc.js:331
proc @ proc.js:280
resolveIterator @ proc.js:466
runCallEffect @ proc.js:527
runEffect @ proc.js:445
next @ proc.js:325
currCb @ proc.js:398
end @ proc.js:366
task.cont @ proc.js:109
next @ proc.js:331
proc @ proc.js:280
resolveIterator @ proc.js:466
runCallEffect @ proc.js:527
runEffect @ proc.js:445
next @ proc.js:325
currCb @ proc.js:398
_tickCallback @ internal/process/next_tick.js:109
redux-logger.js:1  action READ_RESOURCES_SUCCEEDED @ 13:44:35.090
utils.js:258 uncaught at fetchIssues TypeError: Function.prototype.bind.apply(...) is not a constructor
    at http://localhost:1212/dist/main-bundle.js:30221:24
    at instantiate (http://localhost:1212/dist/main-bundle.js:30229:9)
    at IssueItem (eval at proxyClass (http://localhost:1212/dist/main-bundle.js:30236:22), <anonymous>:4:17)
    at mountIndeterminateComponent (webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:8032:15)
    at beginWork (webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:8221:16)
    at performUnitOfWork (webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:10224:16)
    at slowWorkLoopThatChecksForFailedWork (webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:10310:28)
    at workLoop (webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:10278:7)
    at HTMLUnknownElement.callCallback (webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:542:14)
    at Object.invokeGuardedCallbackDev (webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:581:16)
log @ utils.js:258
logError @ proc.js:220
(anonymous) @ proc.js:503
exec @ scheduler.js:23
flush @ scheduler.js:64
asap @ scheduler.js:37
runPutEffect @ proc.js:496
runEffect @ proc.js:445
next @ proc.js:325
currCb @ proc.js:398
end @ proc.js:366
task.cont @ proc.js:109
next @ proc.js:331
proc @ proc.js:280
resolveIterator @ proc.js:466
runCallEffect @ proc.js:527
runEffect @ proc.js:445
next @ proc.js:325
currCb @ proc.js:398
end @ proc.js:366
task.cont @ proc.js:109
next @ proc.js:331
proc @ proc.js:280
resolveIterator @ proc.js:466
runCallEffect @ proc.js:527
runEffect @ proc.js:445
next @ proc.js:325
currCb @ proc.js:398
_tickCallback @ internal/process/next_tick.js:109
redux-logger.js:1  action READ_RESOURCES_PENDING @ 13:44:35.355
redux-logger.js:1  action resources/SET_META @ 13:44:35.687
redux-logger.js:1  action READ_RESOURCES_SUCCEEDED @ 13:44:35.693

**Comment by JimTim** [comment]
Maybe this very long log helps you?

**Comment by VladimirPal** [comment]
@JimTim 
Try please 2.5.6 https://github.com/web-pal/chronos-timetracker/releases/tag/v2.5.6

**Comment by JimTim** [comment]
Okay, I'm on it, Thank you

**Comment by JimTim** [comment]
Still white...

**Comment by VladimirPal** [comment]
But we finally cath the error, it will be fixed soon.

**Comment by JimTim** [comment]
Wow, I'm really impressed. Thank you very much.

**Comment by VladimirPal** [comment]
@JimTim Download again 2.5.6(files was replaced) and try it please.

**Comment by JimTim** [comment]
Now it is stuck on fetching projects and issues...
<img width="475" alt="bildschirmfoto 2018-02-12 um 14 57 40" src="https://user-images.githubusercontent.com/6737248/36100061-357b8bb0-1005-11e8-875e-fde923df9e02.png">

**Comment by VladimirPal** [comment]
Try 2.5.7 it should work
https://github.com/web-pal/chronos-timetracker/releases/tag/v2.5.7

**Comment by JimTim** [comment]
Fetching now working again, Still white page after loading specific project :-)

**Comment by VladimirPal** [comment]
White page mean no issues? Could you attach a screenshot?

**Comment by JimTim** [comment]
White page means this (after selecting the specific "special" project):
<img width="1070" alt="bildschirmfoto 2018-02-12 um 15 49 01" src="https://user-images.githubusercontent.com/6737248/36102328-4b0edda4-100c-11e8-8d08-34d2d2ca015d.png">

**Comment by VladimirPal** [comment]
Duplicate https://github.com/web-pal/chronos-timetracker/issues/70

**Comment by VladimirPal** [comment]
I have no idea how could it happen:)
Could you download debug version - https://github.com/web-pal/chronos-timetracker/releases/download/v2.5.7/Chronos-2.5.7.debug.dmg
And send us screenshot from debug console.

**Comment by JimTim** [comment]
After click on the specific project (right upper combobox)

![bildschirmfoto 2018-02-12 um 16 19 49](https://user-images.githubusercontent.com/6737248/36103833-b0f99524-1010-11e8-84de-58db8ad2c75f.png)

![bildschirmfoto 2018-02-12 um 16 20 08](https://user-images.githubusercontent.com/6737248/36103844-b848235e-1010-11e8-8fa2-d33ced071cd4.png)

**Comment by VladimirPal** [comment]
@JimTim 
Could you download debug version again(same url), reinstall it, and send  last special log
```
==========SPECIAL LOG FOR JIMTIM============
```

**Comment by JimTim** [comment]
Sorry, that would contain too much sensitive data. Can I look for something that should be there?

**Comment by VladimirPal** [comment]
Could you check issue object, does it have fields?
```
{
  fields: {
    issuetype,
    summary,
    priority,
    status,
  }
}
```

**Comment by VladimirPal** [comment]
Could you download debug version again, it have potential solution.
BTW, 2.4.7 version works fine even with the "problem project"?

**Comment by JimTim** [comment]
I see several log outputs between Special Log for jimtim. These are usually two objects. 

- The first object also has a number of objects. The value "fields" are attached to these objects. In total there are 10 objects here

- The second object in my log is then an issue object. This object is available 10 times in total

After all issue objects have been processed, there is "my" log output a few more times.
However, only the first object is defined in it. This always has different objects.
The second object, that always had the issues, is now undefined. This happens 6 times and then the red error appears.

2.4.7 shows some issues on the left side, but then gets this error.
<img width="479" alt="bildschirmfoto 2018-02-12 um 17 11 20" src="https://user-images.githubusercontent.com/6737248/36106520-e3bbf72a-1017-11e8-9113-80f7f80d23ca.png">

**Comment by VladimirPal** [comment]
@JimTim 
Check 2.5.8 please, i hope it will be the last one:)
https://github.com/web-pal/chronos-timetracker/releases/tag/2.5.8

**Comment by JimTim** [comment]
Wuhuhuhu, wow. Now it is working! I can finally retrieve the issues and can't get a white page anymore, what was the fix?

**Comment by VladimirPal** [comment]
@JimTim This was a series of fixes, different jira servers in some cases response different data structure, we just adapted app to your server.
