### ISSUE TITLE
Blank (white) screen

### ISSUE THREAD

**Issue by majsternc** [web-pal/chronos-timetracker#70]
## Expected Behavior
After starting up Chronos I should see login screen

## Actual Behavior
I see white board in Chronos window.
I have to
rm -R ~/.config/Chronos/storage and then start it up again to see Chronos windows properly. 
I have to do it every time when I want to start Chronos.

![screenshot_20180212_121419](https://user-images.githubusercontent.com/36298580/36094459-a3d82b20-0fee-11e8-8227-bc7798ed8a9b.png)

## Steps to Reproduce the Problem

  1. Start OS
  2.Start Chronos
  3. Close Chornos
  4. Start Chronos

## Specifications

  - Chronos-timetracker version: 2.5.4
  - OS: Kubuntu 16.04 LTS (KDE)

**Comment by VladimirPal** [comment]
@majsternc check 2.5.8 please, it should work, let us know please.

**Comment by majsternc** [comment]
nope, it still appears :/

**Comment by VladimirPal** [comment]
@majsternc Could you check it again please, it seems like we removed your automatic issue report accidentally

**Comment by VladimirPal** [comment]
@majsternc I suppose it happens because we store passwords using keytar lib and your distributive do not support it.
Check it please - https://github.com/atom/node-keytar#on-linux and try to install libsecret

**Comment by VladimirPal** [comment]
@majsternc It would be great if you type two words on marketplace reviews - https://marketplace.atlassian.com/plugins/com.web-pal.jira.plugins.chronos/cloud/reviews
something like ```good``` or ```bad``` will be enought, also github star :star: will help us too. Thank you. :pray: :metal:
