### ISSUE TITLE
Display remaining time progress bar

### ISSUE THREAD

**Issue by VladimirPal** [web-pal/chronos-timetracker#74]
During time tracking we need to display remaining time progress bar. It need to be shown only in case if remaining time exist, otherwise what's the point right?

P.S
Help wanted! If someone wants to handle this issue, let us know please.

**Comment by feldifux** [comment]
It would be beneficial to show in the log work dialog this info:
* how long was logged in total until now (by you and in total, similar what you show in the reports tab)
* and what the remaining time is.

If there is no remaining time set yet, still allow to set one in the log work dialog.

**Comment by VladimirPal** [comment]
2.7.4
