### ISSUE TITLE
STOP button hides

### ISSUE THREAD

**Issue by majsternc** [web-pal/chronos-timetracker#75]
## Expected Behavior
STOP button should be visible without matter of Chronos window scale

## Actual Behavior
I have to enlarge Chronos windows much on right side to see STOP button.

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Chronos-timetracker version: 2.5.9
  - OS: Kubuntu

**Comment by Architektor** [comment]
would you kindly attach a screenshot @majsternc ?
I just tried on ios and minimum app width seems to be fine, maybe you have a long issue key or something like that?

**Comment by VladimirPal** [comment]
If someone know how reproduce it, let us know please.
