### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by feldifux** [web-pal/chronos-timetracker#77]
## Expected Behavior
A tool like Chronos should be in idle mode most of the time and take almost 0% CPU usage. For both scenarios when the app is minimized (not focused) and also when it is active.

## Actual Behavior
CPU usage is constantly >20%

## Steps to Reproduce the Problem

  1. Start Chronos
  1. See CPU Usage in Windows

## Specifications

  - Chronos-timetracker version: 2.5.11
  - OS: Windows 10

**Comment by VladimirPal** [comment]
I'm afraid we can't fix it, it's usual issue of electron app

**Comment by feldifux** [comment]
How can this be an Electron issue?
I'm also using other apps that are based on Electron like Slack or Franz, and none of these has this issue.

**Comment by Architektor** [comment]
@feldifuxI can't reproduce it either, for me, Chronos is almost always at 0.0 - 1.0 % CPU time.
Is it always 20% for you, or it grows to 20% at some point in time? Does it turns to 20% instantly or builds up for some time? For further investigation, you probably need to use the chrome profiler to take the runtime snapshots and detect the problem.

**Comment by feldifux** [comment]
It is at 20% right after app start

How would I use the chrome profiler with the Chronos app?

**Comment by guy881** [comment]
I have the same problem on Windows 10, Chronos is usually around 16% CPU usage. I also have Mattermost which is another Electron app and the problem doesn't occur.

@Architektor, I can record that profile for you, if you want. :)
