### ISSUE TITLE
Bug: Search issues does not work and stalls all network requests. Also searching for updates causes all network requests to stall.

### ISSUE THREAD

**Issue by feldifux** [web-pal/chronos-timetracker#78]
## Expected Behavior
Searching for issues should work. Such as searching for chronos app updates. ;)

## Actual Behavior
It does not. The network requests are stalled and the app is not usable afterwards any more (no more network requests get through), if either any search term for the issues is entered, or if Settings / Updates is opened.

## Steps to Reproduce the Problem

  1. Enter any search term to search issues
  1. No more network requests are working

## Specifications

  - Chronos-timetracker version: 2.5.11
  - OS: Windows 10

**Comment by VladimirPal** [comment]
@feldifux Fixed

**Comment by feldifux** [comment]
in which version?
