### ISSUE TITLE
Bug: after creating a new issue, window is not closed and whole app needs to be closed

### ISSUE THREAD

**Issue by feldifux** [web-pal/chronos-timetracker#79]
## Expected Behavior
After creating a new task, the new task window should disappear.

## Actual Behavior
The new task window stays there and is not closable. The whole Chronos app needs to be restarted after that, which makes new issue creation unusable. Fully reproducable.

## Steps to Reproduce the Problem

  1. Create new issue
  1. Window keeps displayed and is not closable

## Specifications

  - Chronos-timetracker version: 2.5.11
  - OS: Windows 10

**Comment by VladimirPal** [comment]
@feldifux Could you confirm that it works now?

**Comment by feldifux** [comment]
Works perfect now, thanks!
