### ISSUE TITLE
Feature Request: Allow to edit task fields

### ISSUE THREAD

**Issue by feldifux** [web-pal/chronos-timetracker#80]
## Expected Behavior
show an "Edit issue" button which opens the edit issue dialog from Jira. This would allow changing for example components, labels, description, or whatever custom field a user has added to the edit screen scheme.

## Actual Behavior
No editing possibility, need to switch to web ui for making task edits.

**Comment by VladimirPal** [comment]
@feldifux Could you check it please?
It would be great if you type two words on marketplace reviews - https://marketplace.atlassian.com/plugins/com.web-pal.jira.plugins.chronos/cloud/reviews
something like ```good``` or ```bad``` will be enought. Thank you. :pray: :metal:

**Comment by feldifux** [comment]
I already did. ;)

Works nicely now, thanks!
The only thing is that it takes quite long to open the dialog (~5-10 seconds). Is there a reason or quick fix for that?

**Comment by VladimirPal** [comment]
@feldifux Check 2.5.15 please

**Comment by feldifux** [comment]
Works a lot faster now, thanks a ton, well done!
You guys are amazing and super-fast :)

**Comment by VladimirPal** [comment]
@feldifux Thanks, but since the app works pretty stable we will freeze development at least for a  month, to focus on jira timesheet plugin.
