### ISSUE TITLE
Feature request: worklog comment as a required item

### ISSUE THREAD

**Issue by skrupenin** [web-pal/chronos-timetracker#81]
## Expected Behavior
Person starts timer working on an issue
Person stops timer, Chronos displays input box to type a worklog description
Worklog with a description is recorded

## Actual Behavior
Person starts timer working on an issue
Person stops timer
Worklog is recorder

## Specifications
Option Required for Worklog description should be configured in settings

**Comment by VladimirPal** [comment]
@skrupenin  v2.6.4
