### ISSUE TITLE
Comments tab gets too wide if there are comments with long strings (URL, for example)

### ISSUE THREAD

**Issue by skrupenin** [web-pal/chronos-timetracker#83]
## Expected Behavior
All tabs of issue should be visible and stay well-formatted

## Actual Behavior
Comments tab extends to a width to render comments. No line breaks added to long strings (for example, URL).
Since there is no horizontal scroll-bar in comments window, all comments got cut.

See sample: https://monosnap.com/file/EQYG742VIdP3nQqHWcrgcOyxB5w51S

## Steps to Reproduce the Problem

  1. Create a comment with a long string without separators (space, comma, dot..)

## Specifications

  - Chronos-timetracker version: 2.5.14
  - OS: MacOS

**Comment by VladimirPal** [comment]
@skrupenin fixed v2.6.4
