### ISSUE TITLE
Feature request: set the start time of log work to "now - logged time" as default

### ISSUE THREAD

**Issue by feldifux** [web-pal/chronos-timetracker#84]
## Expected Behavior
When logging time manually, set the start time by default to "now - logged time". This is more reasonable because when I log time that time can not be in the future, but the task started in the past, then worked on it, and then logged the time.

If no start date & time was set manually, calculate the start time from the logged time. If it was set manually in the dialog, do not modify the start time.

For example, if time now is 28.2.2018 at 00:20 and I enter 30m to the logged time field, the start day should be set to 27.2.2018 at 23:50 (11:50 pm in US format).

To simplify this, you could also add a checkbox "set start time automatically" and just calculate the start time then when a user presses "Log Work" in the log work dialog and disable the start time input field. You could check this checkbox by default, as nobody will enter time going into the future.

## Actual Behavior
The start time always stays at now, and for proper time logging a user always needs to modify it manually which is slow & tedious, because we cannot enter a time with keyboard but need to use the clumsy time picker for this with mouse.

## Specifications

  - Chronos-timetracker version: 2.5.14
  - OS: Windows

**Comment by VladimirPal** [comment]
@feldifux  v2.6.4

**Comment by feldifux** [comment]
looks good, thanks!

**Comment by feldifux** [comment]
Whenever the logged time is changed, the starting time gets reduced relative to the current start time. it should always be reduced absolute of the current time, not relative of te defined start time.

E.g. if you enter "1h 15m" by writing it in the logged time field, it will deduce the time by 2h 15m from the current time which doesnt make sense.

**Comment by feldifux** [comment]
Thus pls re-open until this is fixed

**Comment by Architektor** [comment]
@feldifux yeah i see, will fix in next patch!
