### ISSUE TITLE
Feature request: see recent worklogs across projects

### ISSUE THREAD

**Issue by feldifux** [web-pal/chronos-timetracker#85]
## Expected Behavior
Would simplify the lengthy process to load tasks from multiple projects. Most of the time, the same tasks are being worked on anyways.

## Actual Behavior
Recent worklogs shows only the logs of the currently selected project.

**Comment by Architektor** [comment]
2.7.0 is out! Please make any favorite filter inside JIRA, and you will be able to use it, edit it and create new JQL filters in Chronos! Works project-wide.
