### ISSUE TITLE
Recent worklogs stays empty if the Jira username got changed

### ISSUE THREAD

**Issue by feldifux** [web-pal/chronos-timetracker#88]
## Expected Behavior
Should show recent worklogs

## Actual Behavior
Nothing is shown, no matter which project is selected.

## Specifications

  - Chronos-timetracker version: 2.5.16-a
  - OS: Windows 10

**Comment by feldifux** [comment]
Also, search issues is not working anymore. :(

**Comment by VladimirPal** [comment]
@feldifux Can't reproduce it, could you check it again, also check previous version

**Comment by feldifux** [comment]
Hm, I just tested it also with 2.5.15 and 2.5.14 and it also does not work there anymore. It definitely did work before.
Any clue why it stopped working now?

**Comment by feldifux** [comment]
Thanks, seems this is not a caching issue.
I also get an error when I try to load the time sheet with the Tempo plugin on mobile. However, in the Tempo "My work" tab from the Tempo plugin on the website, receiving the time logs works.

Any hint how to fix this?

**Comment by feldifux** [comment]
UPDATE: receiving time logs works now again with the Tempo app. I changed my Jira username, then had to update my account settings from the Tempo app and now it works.

However, in Chronos the recent worklogs do not work still. I tried to remove the cache directory, uninstall Chronos, tested with previous Chronos versions, and re-logged in, without success. The recent timelogs are still empty.

Do you cache somehow on your server the login keys? Or what other reasons might there be for this issue?

**Comment by feldifux** [comment]
I tried it again with Chronos version 2.5.14, .15 and the latest 16-a, always cleared the local cache before reinstalling, the recent log is still empty with all of them.

In the mobile Tempo app, this is how I fixed the receiving of data: Go to Settings / Manage Tempo / Reload user information.

It looks like some old user account info is cached in Chronos which prevents the old timelogs from being shown. Do you know how to fix this?

**Comment by feldifux** [comment]
Update: I tried to login with another test user, and there the recent worklog works. So this has something to do with the server login from Jira. In the tempo app all worked after I pressed "Reload user information", i do not know how to fix this with Chronos.

**Comment by VladimirPal** [comment]
@feldifux Honestly i have no idea what it can be :(

**Comment by VladimirPal** [comment]
@feldifux I understand that it may be impossible for you, but you can temporary change password on your account and give me credentials, so i can login and explore the issue.
mail.vpal@gmail.com

**Comment by VladimirPal** [comment]
Fixed

**Comment by feldifux** [comment]
Thanks, you guys are amazing!
