### ISSUE TITLE
Bug: Sprint issues are not filtered out

### ISSUE THREAD

**Issue by Kondamon** [web-pal/chronos-timetracker#94]
## Expected Behavior
When I select board and and an active sprint I just want to see issues for this active sprint and all other issues are filtered out.

## Actual Behavior
Issues from older sprints and also closed issues are shown.

## Steps to Reproduce the Problem

  1. Select board
  2. Select sprint
  3. Look at the issues

## Specifications

  - Chronos-timetracker version: 2.6.2
  - OS: macOS HighSierra 10.13.2

**Comment by VladimirPal** [comment]
@Kondamon  check v2.6.4 please

**Comment by Kondamon** [comment]
@VladimirPal it's working thank you for the quick fix!
