### ISSUE TITLE
When deleting a timelog entry, it displays "Something is wrong" and need to restart the app

### ISSUE THREAD

**Issue by feldifux** [web-pal/chronos-timetracker#96]
## Expected Behavior
The first deletion of any timelog works fine. A second deletion, shows the screen "Something went wrong." and the app needs to be restarted.

Update: also the first deletion sometimes shows the something went wrong screen. The timelog is deleted actually, which can be seen after restarting the app.

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Chronos-timetracker version:
  - OS:

**Comment by VladimirPal** [comment]
@feldifux Check 2.6.3 please

**Comment by feldifux** [comment]
This bug is still there.

**Comment by VladimirPal** [comment]
@feldifux Could you check 2.6.4 please

**Comment by feldifux** [comment]
looks to work fine now

**Comment by feldifux** [comment]
still occurs, i cannot reproduce it 100% though

**Comment by feldifux** [comment]
is still happening, occurs 100% reproducable with 2.7.3 every time i want to delete a timelog

**Comment by VladimirPal** [comment]
@feldifux Could you check the last version, please?
